Sklearn中的统一数据数据输入格式 (n_sample,n_featuers)

In [1]:
import numpy as np
X = np.arange(6).reshape(3,2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

# Method ：.fit_transform(X)

- 【默认】$[1,x_1,x_2,x_2^2,x_1x_2,x_2^2]$ 

In [2]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)
res = poly.fit_transform(X)
print(res)
print(poly)

[[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]
PolynomialFeatures(degree=2, include_bias=True, interaction_only=False,
                   order='C')


- 只有交叉项没有平方项$[1,x_1,x_2,x_1x_2]$ 

In [3]:
poly = PolynomialFeatures(degree=2,interaction_only=True)
res = poly.fit_transform(X)
print(res)

[[ 1.  0.  1.  0.]
 [ 1.  2.  3.  6.]
 [ 1.  4.  5. 20.]]


- 没有常数项 $[x_1,x_2,x_2^2,x_1x_2,x_2^2]$ 

In [4]:
poly = PolynomialFeatures(degree=2,include_bias=False)
res = poly.fit_transform(X)
print(res)

[[ 0.  1.  0.  0.  1.]
 [ 2.  3.  4.  6.  9.]
 [ 4.  5. 16. 20. 25.]]


# Attributes

In [11]:
poly = PolynomialFeatures(degree=2)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [12]:
poly.interaction_only

False

In [13]:
poly.order

'C'

In [14]:
poly.powers_

array([[0, 0],
       [1, 0],
       [0, 1],
       [2, 0],
       [1, 1],
       [0, 2]], dtype=int64)

这个属性值解释了每个维度的由来，比如第一维维度是常数项1,对应$[0,0]$,其实就是 $x_1^0\cdot x_2^0$